services:
  - type: web
    name: dicom2nifti-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y dcm2niix && pip install -r requirements.txt
    startCommand: gunicorn app:app
